"""
Advisor Agent — 分析 JD 趋势和投递数据，生成每周建议报告。

分工：
  - 统计分析（技能词频、投递转化率）: 纯 Python，不走 LLM
  - 建议叙述生成: Gemini
"""

import json
import os
from collections import Counter
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path

from google import genai
from google.genai import types

from jobseeking_agent.models.application import Application, ApplicationStatus
from jobseeking_agent.models.job import Job, JobStatus
from jobseeking_agent.models.user_profile import UserProfile

MODEL = "gemini-2.5-flash"
REPORTS_DIR = Path("data/reports")

ADVISOR_SYSTEM = """You are a career advisor generating a concise weekly report for a job seeker.
Be specific and actionable. Avoid vague advice like "keep applying" or "improve your skills".
Each recommended action should name a concrete skill, resource, or next step."""

ADVISOR_SCHEMA = types.Schema(
    type=types.Type.OBJECT,
    properties={
        "market_summary": types.Schema(type=types.Type.STRING),
        "skill_gap_analysis": types.Schema(type=types.Type.STRING),
        "recommended_actions": types.Schema(
            type=types.Type.ARRAY,
            items=types.Schema(type=types.Type.STRING),
        ),
    },
    required=["market_summary", "skill_gap_analysis", "recommended_actions"],
)


@dataclass
class AdvisorReport:
    generated_at: datetime
    # Stats (computed by Python)
    total_jobs_analysed: int
    top_missing_skills: list[dict]   # [{"skill": str, "count": int}]
    top_present_skills: list[dict]   # skills user has that are in demand
    app_stats: dict                  # total, applied, response_rate
    # Narrative (generated by LLM)
    market_summary: str = ""
    skill_gap_analysis: str = ""
    recommended_actions: list[str] = field(default_factory=list)

    def to_text(self) -> str:
        lines = [
            f"ADVISOR REPORT — {self.generated_at.strftime('%Y-%m-%d')}",
            "=" * 60,
            "",
            "## Application Stats",
            f"  Jobs in DB:       {self.total_jobs_analysed}",
            f"  Applied:          {self.app_stats.get('applied', 0)}",
            f"  Response rate:    {self.app_stats.get('response_rate', 'N/A')}",
            "",
            "## Top Skills You're Missing (from JDs)",
        ]
        for item in self.top_missing_skills[:10]:
            lines.append(f"  [{item['count']:>3}x]  {item['skill']}")

        lines += [
            "",
            "## Your Skills in Demand",
        ]
        for item in self.top_present_skills[:10]:
            lines.append(f"  [{item['count']:>3}x]  {item['skill']}")

        lines += [
            "",
            "## Market Summary",
            self.market_summary,
            "",
            "## Skill Gap Analysis",
            self.skill_gap_analysis,
            "",
            "## Recommended Actions",
        ]
        for i, action in enumerate(self.recommended_actions, 1):
            lines.append(f"  {i}. {action}")

        return "\n".join(lines)


class AdvisorAgent:
    def __init__(self) -> None:
        self.client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    def run(
        self,
        jobs: list[Job],
        applications: list[Application],
        user_profile: UserProfile,
        lookback_days: int = 30,
    ) -> AdvisorReport:
        cutoff = datetime.utcnow() - timedelta(days=lookback_days)
        recent_jobs = [j for j in jobs if j.created_at >= cutoff]
        if not recent_jobs:
            recent_jobs = jobs  # fall back to all jobs if none in window

        user_skill_names = {s.name.lower() for s in user_profile.skills}
        skill_freq = self._count_skill_frequencies(recent_jobs)
        app_stats = self._calc_app_stats(applications, jobs)

        top_missing = [
            {"skill": skill, "count": count}
            for skill, count in skill_freq.most_common(30)
            if skill.lower() not in user_skill_names
        ][:15]

        top_present = [
            {"skill": skill, "count": count}
            for skill, count in skill_freq.most_common(30)
            if skill.lower() in user_skill_names
        ][:10]

        narrative = self._generate_narrative(
            top_missing, top_present, app_stats, user_profile, recent_jobs
        )

        report = AdvisorReport(
            generated_at=datetime.utcnow(),
            total_jobs_analysed=len(recent_jobs),
            top_missing_skills=top_missing,
            top_present_skills=top_present,
            app_stats=app_stats,
            market_summary=narrative.get("market_summary", ""),
            skill_gap_analysis=narrative.get("skill_gap_analysis", ""),
            recommended_actions=narrative.get("recommended_actions", []),
        )

        self._save_report(report)
        return report

    # ── Pure Python analysis ──────────────────────────────────────────────────

    def _count_skill_frequencies(self, jobs: list[Job]) -> Counter:
        counter: Counter = Counter()
        for job in jobs:
            for skill in job.skills_required:
                counter[skill.strip()] += 1
        return counter

    def _calc_app_stats(self, applications: list[Application], jobs: list[Job]) -> dict:
        total = len(applications)
        applied = total
        responded = sum(
            1 for a in applications
            if a.status in (ApplicationStatus.response_received, ApplicationStatus.closed)
        )
        interviews = sum(
            1 for j in jobs if j.status == JobStatus.interview
        )
        response_rate = f"{responded / total:.0%}" if total else "N/A"
        return {
            "total_jobs": len(jobs),
            "applied": applied,
            "responded": responded,
            "interviews": interviews,
            "response_rate": response_rate,
        }

    # ── LLM narrative ─────────────────────────────────────────────────────────

    def _generate_narrative(
        self,
        top_missing: list[dict],
        top_present: list[dict],
        app_stats: dict,
        user_profile: UserProfile,
        recent_jobs: list[Job],
    ) -> dict:
        target_roles = ", ".join(user_profile.target_roles)
        missing_text = ", ".join(f"{i['skill']} ({i['count']}x)" for i in top_missing[:10])
        present_text = ", ".join(f"{i['skill']} ({i['count']}x)" for i in top_present[:8])
        sample_jd_titles = list({j.title for j in recent_jobs if j.title})[:10]

        prompt = (
            f"## Candidate\nTarget roles: {target_roles}\n"
            f"Current skills: {', '.join(s.name for s in user_profile.skills)}\n\n"
            f"## Job Market Data (last 30 days, {len(recent_jobs)} JDs)\n"
            f"Roles seen: {', '.join(sample_jd_titles)}\n\n"
            f"## Skills in JDs the candidate is MISSING\n{missing_text}\n\n"
            f"## Candidate's skills that ARE in demand\n{present_text}\n\n"
            f"## Application Stats\n"
            f"Applied: {app_stats['applied']}, Response rate: {app_stats['response_rate']}, "
            f"Interviews: {app_stats['interviews']}\n\n"
            "Generate a weekly advisor report with market summary, skill gap analysis, "
            "and 3-5 specific recommended actions."
        )
        response = self.client.models.generate_content(
            model=MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=ADVISOR_SYSTEM,
                response_mime_type="application/json",
                response_schema=ADVISOR_SCHEMA,
            ),
        )
        return json.loads(response.text)

    def _save_report(self, report: AdvisorReport) -> None:
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        filename = f"advisor_{report.generated_at.strftime('%Y%m%d_%H%M')}.txt"
        (REPORTS_DIR / filename).write_text(report.to_text(), encoding="utf-8")
